### ISSUE TITLE
Torus Build Error (Rollup Apps)

### ISSUE THREAD

**Issue by aaronbarnardsound** [blocknative/onboard#219]
The Torus SDK currently errors when trying to build in a Rollup app.

<img width="576" alt="Screen Shot 2020-02-21 at 11 16 18 AM" src="https://user-images.githubusercontent.com/29873495/74992299-c8939280-549b-11ea-8fd8-3c8b56ca28b2.png">

I have replicated this in a basic Rollup build using Torus Embed directly without Onboard.

@torusresearch Have you guys successfully ran Torus Embed in a Rollup app? If so, is there a specific config parameter or plugin that is necessary?

**Comment by chaitanyapotti** [comment]
Hi
Do you have a sample repo where i can test this.?

**Comment by aaronbarnardsound** [comment]
Thanks @chaitanyapotti I will check it out 👍

**Comment by aaronbarnardsound** [comment]
Hey @chaitanyapotti that boilerplate seems to use Webpack under the hood as well as Rollup, which seems to solve the problem (as Webpack includes all of the node built-ins by default). I still haven't been able to get it to build in a Rollup app without Webpack. Could you see if you can get Torus working with the [official Rollup App template](https://github.com/rollup/rollup-starter-app) and let me know how you go?

**Comment by chaitanyapotti** [comment]
There are a bunch of things here.
Torus-embed currently expects to have @babel/runtime as a runtime dependency.
[Here's](https://github.com/chaitanyapotti/rollup-starter-torus-embed) a sample repo i created which isn't fully working.! But, it has all the polyfills.!
We release torus in such a way because most people have build tools (webpack and rollup) and we don't want to pollute global polyfills.
Right now, for those who don't have build tools, we encourage them to use torus by either pulling from source and creating a build for themselves or use the pre packaged build available [here](https://gist.github.com/chaitanyapotti/733405286923fa047af4cb26d167acd4).
We are planning to release torus-embed in the future with esm, commonjs and umd builds.

**Comment by chaitanyapotti** [comment]
Hey @aaronbarnardsound , we just released a new version v1.3.0 which fixes this issue. 
The rollup-starter-app now works with this latest version of torus-embed.
