### ISSUE TITLE
Connect imToken,  WalletConnect , Coinbase

### ISSUE THREAD

**Issue by yunlonglee** [blocknative/onboard#435]
When connect imToken,  WalletConnect , Coinbase wallet, network will fetch rpc url too may time.
Around 1 sec fetch 1 time.
![messageImage_1600924403861](https://user-images.githubusercontent.com/28677753/94107710-9b172900-fe70-11ea-9632-420bf5580bda.jpg)

**Comment by aaronbarnardsound** [comment]
Hi @yunlonglee, could you check to see what the requests are. I am seeing regular `eth_blockNumber` requests which come from the `web3-provider-engine` for block polling, which unfortunately, I don't think can be switched off. 

I did also notice that the WalletConnect provider is not disconnecting properly(which also uses the web3-provider-engine), so if you were to select WalletConnect and then switch to imToken, then there would be two block trackers polling at once.

I will find out if WalletConnect has fixed the `provider.stop` issue.

![Screen Shot 2020-09-25 at 3 39 43 pm](https://user-images.githubusercontent.com/29873495/94230520-7a6cd300-ff45-11ea-912e-2e1357c65005.png)

**Comment by vince0656** [comment]
Having issues too with `web3-provider-engine`

![image](https://user-images.githubusercontent.com/15893673/94281073-14cd1680-ff46-11ea-80f2-09b91c703aed.png)

**Comment by vince0656** [comment]
All hardware wallet connections and wallet connect is not working

**Comment by cmeisl** [comment]
@vince0656 The screenshot of errors above suggest that you are being rate limited by your provider, Infura in this case. Since the provider is determined by your wallet selection, which wallet were you using when you saw those errors?

The `PollingBlockTracker` is a function in your wallet (e.,g. Metamask has it). Onboard does not call Infura. Only the wallets that Onboard connects to the Dapp will call Infura, either through an explicit `RPC_URL` setting in the Onboard config on init, or internal to that wallet.

**Comment by vince0656** [comment]
@cmeisl this issue appears as soon as I select WalletConnect or either of the hardware wallets: Trezor or Ledger. I don't experience the issue when using metamask

**Comment by aaronbarnardsound** [comment]
WalletConnect isn't disconnecting properly so will continue to poll after a new wallet has been selected. I have raised an issue on the repo here - https://github.com/WalletConnect/walletconnect-monorepo/issues/363

It seems that Infura must have changed their rate limits recently. In the short term #436 should solve an issue where the browser might get stuck in a loop trying to import the provider engine when it throws an error.

The long term solution is that we need to migrate to something other than `web3-provider-engine` as it is no longer maintained and seems to have a lot of issue. WalletConnect seem to be in the process of also migrating away from `web3-provider-engine` and seem to be working towards using [eth-provider](https://github.com/floating/eth-provider) instead which we could also consider using. Will need to do some more research.

**Comment by aaronbarnardsound** [comment]
Fixed via #467 and by using the `blockPollingInterval` [initialization parameter](https://docs.blocknative.com/onboard#blockpollinginterval-optional-default-4000)

**Comment by brunomenezes** [comment]
Hi @aaronbarnardsound, I am "bringing" this issue to life again because I saw you open an [issue](https://github.com/WalletConnect/walletconnect-monorepo/issues/363) on WalletConnect repo (still open). I stumbled upon the same issue that you mention about after a new wallet is selected the polling is still happening. Is the long term solution you mentioned still on the table? I am using onboardJS@1.36.0


PS: Just an extra situation with that undying polling that we hit by mistake is that if the first connection fails (and keep failing) the initialization parameter config from **onboardJS** does not apply and the underlying retry interval of ~400ms will apply.
