### ISSUE TITLE
Allow the app to determine if a modal popup will be shown on the walletSelect call

### ISSUE THREAD

**Issue by jeffywu** [blocknative/onboard#458]
If the wallet has approved access to the app but is not logged in, when walletSelect is called the login modal will pop up. This can be a little annoying to have modal pop ups appear unexpectedly in the UI. It would be nice for the app to know if a login modal will be triggered on the walletSelect call and determine what to do in that situation.

Really liking the library so far, works great for us!

**Comment by aaronbarnardsound** [comment]
Hey @jeffywu the login modal is triggered by a call to `onboard.walletCheck()`. A call to `onboard.walletSelect()` will only ever trigger the wallet selection modal. We separated those two functions specifically so that apps could control the onboarding flow UX.

So to achieve what you are describing, you can call `onboard.walletSelect()` and allow the user to select a wallet. You can also pass in a wallet name to auto select a wallet if the user has already connected their wallet to your app to avoid showing the wallet select modal. 

Once the user has a wallet selected you can then check your state that is connected to the `address` subscription. If you have an address, then the user is logged in and connected and a call to `walletCheck` _will not_ show the login/connect modal. If you don't have an address, then the user is either not logged in or will need to approve access to accounts, so in this case a call to `walletCheck` _will_ display the login/connect modal. 

I think this is a simple way of solving your use case without the need to modify the Onboard API.
Let me know if that makes sense.

**Comment by jeffywu** [comment]
@aaronbarnardsound, thanks for the detailed reply here. Gave this a whirl and I got what I needed. Will go ahead and close.
