### ISSUE TITLE
WalletConnect: this.send is not a function

### ISSUE THREAD

**Issue by itsmnthn** [blocknative/onboard#474]
onboard to connect using WalletConnect causing an error after the scanning QR code, and then getting eth address using the web3 object created from the returned provider. WalletConnet works alone as expected.
```
Uncaught (in promise) TypeError: this.send is not a function
    at 48c68d3.js:2
    at Generator.next (<anonymous>)
    at 48c68d3.js:2
    at new Promise (<anonymous>)
    at Module.A (48c68d3.js:2)
    at request (48c68d3.js:2)
    at request (bfb900b.js:2)
    at e.d.send (bfb900b.js:2)
    at w (bfb900b.js:2)
    at C.c (bfb900b.js:2)
```
![image](https://user-images.githubusercontent.com/25129674/103211160-71691480-492d-11eb-9a77-5ea41c92a659.png)
![image](https://user-images.githubusercontent.com/25129674/103212577-2cdf7800-4931-11eb-8263-a0f7f64e9705.png)

**Comment by dmarzzz** [comment]
Hello, would you mind detailing a little bit more about how to recreate this issue because I cannot recreate at the moment. Hopefully we can get this resolved asap :)

**Comment by dzek69** [comment]
@itsmnthn you have closed this without any info.

how did you resolve this issue? I am having the same thing now

**Comment by itsmnthn** [comment]
@dzek69 I had an issue because of the scope of `this` object, changed function to arrow function, and able to solve because of access to `this`

[Here is my implementation check it out](https://github.com/itsmnthn/onboard-nuxt/blob/main/components/login.vue#L112-L117)

**Comment by dzek69** [comment]
@itsmnthn that's weird, because after my analyze the problem seems to me to be fixable either from onboard internals or walletconnect side and shouldn't be fixable from the onboard config. I have arrow function there just like you are but still I get this issue.

Walletconnect dev even announced a fix: https://github.com/WalletConnect/walletconnect-monorepo/issues/384#issuecomment-769682914 but the current version released yestarday is not fixing it for me so I think this particular fix is not released yet.

Thanks for your reply anyway :)

**Comment by itsmnthn** [comment]
> Edit: Maybe your fix fixes just some of the cases? Can you try Walletconnect with the MetaMask app?

It works for me using MetaMask and other WallectConnect supported apps. Maybe try it out in the empty project and then see what happens 👍🏻
