### ISSUE TITLE
Clicking "Dismiss" in OnBoard modals should flush localstorage if set

### ISSUE THREAD

**Issue by swaylock** [blocknative/onboard#506]
Gonna be hard to provide context for this issue, but I'll try.

The way OnBoard is coded, it seems you must have multiple buttons in your wallet connection UI/UX, as exemplified by the demo application:

<img width="606" alt="onboard" src="https://user-images.githubusercontent.com/23582496/110226600-a9e51b80-7ea5-11eb-84a6-13e636b137c3.png">

In our UI, we are wanting to present something much simpler: A single button the user interacts with -- very similar to connection UI/UX on 1Inch exchange.

For the current state of the problem I'm running into, try the following scenario in a browser:

1. Disable the Authereum wallet if it's enabled on your browser (i use brave and never installed it so that's my starting point).
2. Navigate to the demo application https://reactdemo.blocknative.com/
3. Click select a wallet and choose Authereum. You should get a popup dialog and some sort of error message.
4. Refresh the page or close the tab and re-open the demo app.
5. The Authereum connection dialog will pop again. This is because the demo app has saved your selection to localstorage and trying to reload Authereum because you selected it. 
6. Now here's the crux of the problem. Unless you present the user with multiple buttons, for example, "Select another wallet" or "Reset wallet state" or something similar, they will be stuck with the Authereum wallet dialog continually popping up. Or, even if you can coordinate all the logic necessary to deal with automatically reconnecting based on previous selection into a single button, the user will still need to close the unwanted popup and then click the connect button again and hopefully it will all work out.

What I'm proposing is an improvement by providing a way to flush saved wallet selection from localstorage from the Onboard modal dialogs. I'm suggesting we use the  "Dismiss" button (perhaps it should be renamed to "Cancel"?)

![screenshot-reactdemo blocknative com-2021 03 06-18_39_27](https://user-images.githubusercontent.com/23582496/110227333-0ba88400-7eac-11eb-8702-e3332018e919.png)

PR coming shortly.

**Comment by aaronbarnardsound** [comment]
Hey @swaylock, thanks for detailing your issue / use case and also creating a PR for it :)

We have tried to design Onboard to be as flexible as possible so that it can be used for various Onboarding flows but without having infinite configuration options that make it more complex and harder to understand. I think that caching the wallet selection and managing that cache can stay out of the Onboard library since it is up to the app to decide whether to implement this or not.

We'd be open to a change that replaces the "Dismiss" button with a "Switch Wallet" button since the user can dismiss the modal via the close icon in the top right.

Could I suggest a couple of patterns that might solve your issue that don't require changes to the library itself?

One option is that you could delete the wallet selected cache if the wallet checks don't pass so that when a user clicks the dismiss button (or exits the wallet checks for any other reason), the next time they click connect, they will be shown the wallet selection modal:

```javascript
const readyToTransact = await onboard.walletCheck()

if (!readyToTransact) {
  window.localStorage.removeItem('selectedWallet')
}
```

Another option would be to keep track of how many times your connect button has been clicked. If it is greater than 1, then don't use the cached wallet:

```javascript
let connectClicks = 0

async function connect() {
  connectClicks = connectClicks + 1
  const cachedWallet = connectClicks > 1 ? null : window.localStorage.getItem('selectedWallet')
  const walletSelected = await onboard.walletSelect(cachedWallet)
  const readyToTransact =  walletSelected && await onboard.walletCheck()
  
  return readyToTransact
}
```

**Comment by swaylock** [comment]
@aaronbarnardsound thanks for the response. I really like your first option -- clearing localstorage if the checks fail. Simple and effective. Wish I had thought of that in the first place! 

Guess we can close this issue and PR?

Thanks again...

**Comment by aaronbarnardsound** [comment]
Hey @swaylock, awesome, I am glad that helps! Yes I will close the issue and PR since your issue is solved for the moment.
