### ISSUE TITLE
[Bug]: Ronin wallet implementation doesn't work

### ISSUE THREAD

**Issue by shoxv** [blocknative/onboard#767]
### Current Behavior

The ronin wallet implementation isn't working properly. Even when Ronin wallet is installed, it's not able to detect or interact with the wallet. It looks like the code is looking for `window.ronin` which doesn't actually exist even when Ronin wallet is installed.
@ducthotran2010 

### Expected Behavior

Selecting 'Ronin' wallet should pop up the extension / connection request.

### Steps To Reproduce

1. Navigate to https://reactdemo.blocknative.com/
2. Install and login to ronin wallet
3. Click `Select a Wallet`
4. Select Ronin

### Onboard Version

Latest

### Node Version

14

### What browsers are you seeing the problem on?

Chrome

### Anything else?

https://user-images.githubusercontent.com/6876508/147509970-4011b527-acd8-4eaf-ae8f-4e5c3374ecac.mov

**Comment by taylorjdawson** [comment]
@shoxv I believe this may be a bug with Ronin wallet. As you can see in the PR when testing it was injected under the `ronin` namespace. If it didn't then I would have caught this in testing so I am not sure why now it is not getting injected. cc @ducthotran2010

**Comment by Adamj1232** [comment]
@ducthotran2010 the dev from Ronin/Axie responded to question in PR [here](https://github.com/blocknative/onboard/pull/757#issuecomment-1008721384) - "The wallet now only works on Axie's domains and will open to be used by other domains when the Ronin chain is ready."

Please follow the bellow setup/testing/local development

**Testing/Development**

Due to the Ronin extension restriction, please add 127.0.0.1 dev.skymavis.one in your hosts file /etc/hosts and access dev.skymavis.one:<port> instead of localhost:<port>.

**Closing Issue**
